# Generated by Django 4.2.21 on 2025-06-03 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"], "verbose_name_plural": "Tags"},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-is_complete", "-date"],
                "verbose_name_plural": "Tasks",
            },
        ),
    ]
