# Generated by Django 4.2.21 on 2025-06-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_tag_options_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["is_complete", "-date"],
                "verbose_name_plural": "Tasks",
            },
        ),
    ]
